// <auto-generated />
using HR.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810095909_createDBTables")]
    partial class createDBTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CityName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Gov_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_City_CityName_ar");

                    b.HasIndex("CityName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_City_CityName_en");

                    b.HasIndex("Gov_Id");

                    b.ToTable("City", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address_ar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Address_en")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<int>("City_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("CompLogo")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<string>("CompName_ar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CompName_en")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("City_Id");

                    b.HasIndex("CompName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_CompName_ar");

                    b.HasIndex("CompName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_CompName_en");

                    b.ToTable("Company", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("CountryName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Country_Country_ar");

                    b.HasIndex("CountryName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Country_Country_en");

                    b.ToTable("Country", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Country_Id")
                        .HasColumnType("int");

                    b.Property<string>("GovCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GovName_ar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GovName_en")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("GovName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Governorate_GovName_ar");

                    b.HasIndex("GovName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Governorate_GovName_en");

                    b.ToTable("Governorate", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GradeName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<int>("percentage")
                        .HasColumnType("int");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Grade_GradeName_ar");

                    b.HasIndex("GradeName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Grade_GradeName_en");

                    b.ToTable("Grade", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("Gov_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Company", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("City_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.Country", "Country")
                        .WithMany("Governorates")
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Country", b =>
                {
                    b.Navigation("Governorates");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
