// <auto-generated />
using System;
using HR.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Domain.Models.Authorization.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<byte[]>("ModuleImage")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("ModuleName_ar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ModuleName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("ModuleId");

                    b.HasIndex("ModuleName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Module_ModuleName_ar");

                    b.HasIndex("ModuleName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Module_ModuleName_en");

                    b.ToTable("Modules", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Module_SubModules", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SubModuleId")
                        .HasColumnType("int");

                    b.HasKey("ModuleId", "SubModuleId");

                    b.HasIndex("SubModuleId");

                    b.HasIndex("ModuleId", "SubModuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_Module_SubModules_ModuleId_SubModuleId");

                    b.ToTable("Module_SubModules", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_PermissionName");

                    b.ToTable("Permissions", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_Page_Permissions", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PageId", "PermissionId");

                    b.HasIndex("PageId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PageId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePagePermission_RoleId");

                    b.ToTable("Role_Page_Permissions", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_SubModulePages", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PageId");

                    b.HasIndex("PageId");

                    b.HasIndex("RoleId", "PageId")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_ModulePages_RoleId_PageId");

                    b.ToTable("Role_SubModulePages", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_SubModules", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RoleId");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleId");

                    b.Property<int>("SubModuleId")
                        .HasColumnType("int")
                        .HasColumnName("SubModuleId");

                    b.HasKey("RoleId", "ModuleId", "SubModuleId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubModuleId");

                    b.HasIndex("RoleId", "ModuleId", "SubModuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_RoleModules_RoleId_ModuleId_SubModuleId");

                    b.ToTable("Role_SubModules", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.SubModulePages", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageId"));

                    b.Property<string>("PageName_ar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PageName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar");

                    b.Property<int>("SubModuleId")
                        .HasColumnType("int");

                    b.HasKey("PageId");

                    b.HasIndex("PageName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_ModulePage_PageName_ar");

                    b.HasIndex("PageName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_ModulePage_PageName_en");

                    b.HasIndex("SubModuleId");

                    b.ToTable("SubModulePages", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.SubModules", b =>
                {
                    b.Property<int>("SubModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubModuleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubModuleId"));

                    b.Property<string>("SubModuleName_ar")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("SubModuleName_ar");

                    b.Property<string>("SubModuleName_en")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SubModuleName_en");

                    b.HasKey("SubModuleId");

                    b.HasIndex("SubModuleName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_SubModules_SubModuleName_ar");

                    b.HasIndex("SubModuleName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_SubModules_SubModuleName_en");

                    b.ToTable("SubModules", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.User_Page_Permissions", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "PageId", "PermissionId");

                    b.HasIndex("PageId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PageId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPagePermissions_Unique");

                    b.ToTable("User_Page_Permissions", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Identity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActivatedAccount")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CityName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Gov_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_City_CityName_ar");

                    b.HasIndex("CityName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_City_CityName_en");

                    b.HasIndex("Gov_Id");

                    b.ToTable("City", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address_ar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Address_en")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<int>("City_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("CompLogo")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<string>("CompName_ar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CompName_en")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("City_Id");

                    b.HasIndex("CompName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_CompName_ar");

                    b.HasIndex("CompName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_CompName_en");

                    b.ToTable("Company", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("CountryName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Country_Country_ar");

                    b.HasIndex("CountryName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Country_Country_en");

                    b.ToTable("Country", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Country_Id")
                        .HasColumnType("int");

                    b.Property<string>("GovCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GovName_ar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GovName_en")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("GovName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Governorate_GovName_ar");

                    b.HasIndex("GovName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Governorate_GovName_en");

                    b.ToTable("Governorate", "LookUps");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeName_ar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<string>("GradeName_en")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<int>("percentage")
                        .HasColumnType("int");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeName_ar")
                        .IsUnique()
                        .HasDatabaseName("IX_Grade_GradeName_ar");

                    b.HasIndex("GradeName_en")
                        .IsUnique()
                        .HasDatabaseName("IX_Grade_GradeName_en");

                    b.ToTable("Grade", "LookUps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Module_SubModules", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.Module", "Module")
                        .WithMany("Module_SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Module_SubModules_ModuleId");

                    b.HasOne("HR.Domain.Models.Authorization.SubModules", "SubModule")
                        .WithMany("Module_SubModules")
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Module_SubModules_SubModuleId");

                    b.Navigation("Module");

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_Page_Permissions", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.SubModulePages", "SubModulePage")
                        .WithMany("Role_Page_Permissions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Authorization.Permission", "Permission")
                        .WithMany("Role_Page_Permissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Identity.AppRole", "Role")
                        .WithMany("Role_Page_Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("SubModulePage");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_SubModulePages", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.SubModulePages", "SubModulePage")
                        .WithMany("Role_SubModulePages")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Identity.AppRole", "Role")
                        .WithMany("Role_SubModulePages")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SubModulePage");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Role_SubModules", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.Module", "Module")
                        .WithMany("Role_SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Identity.AppRole", "Role")
                        .WithMany("Role_SubModules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Authorization.SubModules", "SubModule")
                        .WithMany()
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.SubModulePages", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.SubModules", "SubModule")
                        .WithMany("SubModulePages")
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.User_Page_Permissions", b =>
                {
                    b.HasOne("HR.Domain.Models.Authorization.SubModulePages", "SubModulePage")
                        .WithMany("User_Page_Permissions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Authorization.Permission", "Permission")
                        .WithMany("User_Page_Permissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Identity.AppUser", "User")
                        .WithMany("User_Page_Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("SubModulePage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("Gov_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Company", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("City_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.HasOne("HR.Domain.Models.LookUps.Country", "Country")
                        .WithMany("Governorates")
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HR.Domain.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HR.Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HR.Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("HR.Domain.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HR.Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Module", b =>
                {
                    b.Navigation("Module_SubModules");

                    b.Navigation("Role_SubModules");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.Permission", b =>
                {
                    b.Navigation("Role_Page_Permissions");

                    b.Navigation("User_Page_Permissions");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.SubModulePages", b =>
                {
                    b.Navigation("Role_Page_Permissions");

                    b.Navigation("Role_SubModulePages");

                    b.Navigation("User_Page_Permissions");
                });

            modelBuilder.Entity("HR.Domain.Models.Authorization.SubModules", b =>
                {
                    b.Navigation("Module_SubModules");

                    b.Navigation("SubModulePages");
                });

            modelBuilder.Entity("HR.Domain.Models.Identity.AppRole", b =>
                {
                    b.Navigation("Role_Page_Permissions");

                    b.Navigation("Role_SubModulePages");

                    b.Navigation("Role_SubModules");
                });

            modelBuilder.Entity("HR.Domain.Models.Identity.AppUser", b =>
                {
                    b.Navigation("User_Page_Permissions");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.City", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Country", b =>
                {
                    b.Navigation("Governorates");
                });

            modelBuilder.Entity("HR.Domain.Models.LookUps.Governorate", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
